# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Build settings
#theme: minima
# テーマをyatに変更 on April 18th 2022
remote_theme: "jeffreytse/jekyll-theme-yat"

title: MY's Tech Blog
email: minakoyoshino3@gmail.com
author: Minako Yoshino

copyright: "Copyright © 2022 Minako Yoshino"

description: >- # this means to ignore newlines until "baseurl:"
  Webエンジニア転職と個人開発の記録を発信します。

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yoiyoicho.github.io" # the base hostname & protocol for your site, e.g. http://example.com
domain: yoiyoicho.github.io
twitter_username: yoiyoicho
github_username:  yoiyoicho

# Google analytics
google_analytics: G-YHG6PKBK5C

# If you want to generate website sitemap, you can set true
sitemap: true

# If you want to change site language, you can set lang option
lang: "ja"  # default lang is en

# Page default value
defaults:
  home:
    heading: "MY's Tech Blog"
    subheading: "Webエンジニア転職と個人開発の記録"
    banner: "/assets/images/banners/home.jpeg"

# Pagination setting
paginate: 5

# Build settings
# highlighter: none
markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
